server:
  port: 8082
  servlet:
    session:
      timeout: 60M
    encoding:
      charset: utf-8
      enabled: true
      force: true
logging:
  config: classpath:config/logback-spring.xml
#  file:
#    path: /logs/zbs
#  level:
#    org:
#      springframework:
#        web: debug
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  profiles:
    active: dev
#  mvc:
#    static-path-pattern: /static/**,/MP_verify_divyjSQEVfhy6G8X.txt
#  resources:

#    static-locations: classpath:/static